### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by leemember** [leemember/leemember-Blog-Resume#1]
앞으로 남은 작업들

- [ ] Header에 Contact 누르면 SNS 채널 및 이메일 보이도록 모달 띄우기
- [ ] 맨 위로 올라가는 버튼 생성하기
- [ ] 사이드 프로젝트 카드 이미지 넣기
- [ ] 경력 - 프로젝트 가지 넣기
- [ ] 경력 - 게시글이 2개 이상일 때 펼치기 / 접기 버튼 생성
- [ ] 안녕하세요 이모티콘 손 흔드는 모션 넣기
- [ ] 로딩바 넣고 전부 로딩 되면 그때 화면 보여지도록 하기
- [ ] 기술스택 넣기
- [ ] 링크복사 구현하기
- [ ] 마지막으로 코드 리팩토링하기

🔥 **2월 7일까지 완벽하게 다 끝내기** 🔥
